[package]
name = "cras_cbindgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cbindgen = "0.27"
clap = { version = "4.5.4", features = ["derive"] }
