# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# The archive of the golden testdata is used for verifying the correctness
# of CRAS_DSP computation module, which has the following structure:
# ./
# ├── the-quick-brown-fox.raw
# ├── the-quick-brown-fox-eq-out.raw
# ├── the-quick-brown-fox-eq2-out.raw
# ├── the-quick-brown-fox-crossover-out.raw
# ├── the-quick-brown-fox-crossover2-out.raw
# ├── the-quick-brown-fox-dcblock-out.raw
# └── the-quick-brown-fox-drc-out.raw
#
# The file named 'the-quick-brown-fox.raw' represents the golden input.
# Other files with 'out.raw' suffix represent the expected outputs for each
# conputation module. The expected output were generated by the test tools
# located in "/cras/src/dsp/test" that were compiled with the correct
# library. To generate the new expected outputs, run the following command:
#
# $ bazel run //cras/src/dsp/tests:generate_dsp_golden_output [output_directory]
#
# This archive was uploaded to
# https://pantheon.corp.google.com/storage/browser/chromiumos-test-assets-public/tast/cros/audio.
# To update the testdata, settle up the new testdata in the same format,
# calculate the sha256sum of the archive and replace it. Then, uplaod the
# archive to the same place and point the url to the new archive.
#

def cras_dsp_file_deps():
    http_archive(
        name = "the_quick_brown_fox_golden_testdata",
        build_file = "@//:cras/src/dsp/tests/the_quick_brown_fox_golden_testdata.BUILD.bazel",
        sha256 = "47721bea83e6a1f9d259304294d5b3d4ee0f8f17800011023585ae7e28ee1bef",
        url = "https://storage.googleapis.com/chromiumos-test-assets-public/tast/cros/audio/the-quick-brown-fox_20240808.zip",
    )
