/* Copyright (c) 2011 The Chromium OS Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */
#if !defined(_BOARD_WALUIGI_H_)
#define _BOARD_WALUIGI_H_

#define ADHD_INITIALIZE_SOUND_COMMAND      ADHD_MAX98095_INIT_COMMAND
#define ADHD_GPIO_HEADPHONE_INSERT_COMMAND ADHD_MAX98095_HEADPHONE_INSERT
#define ADHD_GPIO_HEADPHONE_REMOVE_COMMAND ADHD_MAX98095_HEADPHONE_REMOVE
#define ADHD_GPIO_MIRCOPHONE_INSERT_COMMAND ADHD_MAX98095_MICROPHONE_INSERT
#define ADHD_GPIO_MIRCOPHONE_REMOVE_COMMAND ADHD_MAX98095_MICROPHONE_REMOVE
#endif
