#!/bin/bash
# Copyright 2024 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

cd "$(dirname ${BASH_SOURCE[0]})/.."
RUST_BACKTRACE=1 find "$(realpath ../../overlays)" -path '*/cras-config/*.ini' \
    -exec bazel run //cras/server/ini:parity_check {} +
