Syntax 4

Comment "HDA Intel PCH Audio"

If.board_ucm1 {
	Condition {
		Type Path
		Path "/usr/share/alsa/ucm/${CardName}/HiFi.conf"
		Mode "read"
	}
	True {
		SectionUseCase."HiFi" {
			File "/../ucm/${CardName}/HiFi.conf"
			Comment "Board UCM1 HiFi Audio"
		}
	}
	False {
		SectionUseCase."HiFi" {
			File "HiFi.conf"
			Comment "Default HiFi Audio"
		}
	}
}
