Syntax 4

SectionVerb {
	Value {
		TQ "HiFi"
	}
}

SectionDevice."Internal Mic".0 {
	Value {
		CapturePCM "hw:${CardId},0"
	}

	If.internal_mic_boost {
		Condition {
			Type ControlExists
			Control "name='Internal Mic Boost Volume'"
			Device "hw:${CardId}"
		}
		True {
			EnableSequence [
				cdev "hw:${CardId}"
				cset "name='Internal Mic Boost Volume' 1"
			]
		}
	}

	If.internal_mic_capture_vol {
		Condition {
			Type ControlExists
			Control "name='Internal Mic Capture Volume'"
			Device "hw:${CardId}"
		}
		True {
			EnableSequence [
				cdev "hw:${CardId}"
				cset "name='Internal Mic Capture Volume' 100%"
			]
		}
	}
}
