[package]
name = "cras_s2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audio_processor = "*"
cras_common = "*"

anyhow = "1.0.75"
libc = "0.2.44"
log = "0.4.17"
once_cell = "1.17.0"
serde = { version = "1.0.52", features = ["derive"]}
serde_json = "1.0.96"
