[package]
name = "dsp_rust"
version = "0.1.0"
authors = ["The Chromium OS Authors"]
edition = "2021"

[dependencies]
anyhow = "1.0.75"
float-cmp = "0.9.0"
libc = "0.2"
nix = "0.28.0"
num-traits = "0.2.15"
itertools = "0.11.0"
