// Copyright 2023 The ChromiumOS Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Syntax:
// DEFINE_FEATURE(name, default_enabled)
DEFINE_FEATURE(CrOSLateBootUnknown, false)
DEFINE_FEATURE(CrOSLateBootDisabledByDefault, false)
DEFINE_FEATURE(CrOSLateBootEnabledByDefault, true)
DEFINE_FEATURE(CrOSLateBootAudioHFPOffload, false)
DEFINE_FEATURE(CrOSLateBootAudioHFPMicSR, false)
DEFINE_FEATURE(CrOSLateBootAudioFlexibleLoopback, false)
DEFINE_FEATURE(CrOSLateBootAudioAPNoiseCancellation, false)
DEFINE_FEATURE(CrOSLateBootCrasSplitAlsaUSBInternal, true)
DEFINE_FEATURE(CrOSLateBootAudioHFPSwb, false)
