# Copyright 2021 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

cc_library(
    name = "cras_types",
    srcs = [
        "cras_audio_format.h",
        "cras_iodev_info.h",
        "packet_status_logger.h",
    ],
    hdrs = [
        "cras_types.h",
    ],
    visibility = [
        "//src/benchmark:__pkg__",
        "//src/server:__pkg__",
    ],
)
